name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: XaCode Version
      description: What version of XaCode are you using? (e.g. 1.11.99)
    validations:
      required: true
  - type: input
    id: windows_version
    attributes:
      label: Windows Version
      description: What version of Windows are you running? (e.g. Windows 11 23H2)
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please explain the steps required to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant logs here. Make sure to remove any sensitive information!
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: checkboxes
    id: secrets_check
    attributes:
      label: Confidential Data Check
      description: Please confirm before submitting.
      options:
        - label: I confirm that I have removed all API keys, access tokens, passwords, and personal paths from the logs and screenshots.
          required: true
