const { app, BrowserWindow } = require('electron');
const path = require('path');

app.whenReady().then(async () => {
  const window = new BrowserWindow({ width: 1280, height: 820, show: false, webPreferences: { preload: path.join(__dirname, 'visual-smoke-preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: false, backgroundThrottling: false } });
  await window.loadFile(path.join(__dirname, '..', 'src', 'desktop', 'renderer', 'index.html'));
  await new Promise((resolve) => setTimeout(resolve, 350));
  const result = await window.webContents.executeJavaScript(String.raw`(async () => { try {
    const composerModelIcon = document.querySelector('#modelIcon .provider-svg');
    const composerModelIconAligned = Boolean(composerModelIcon) && getComputedStyle(composerModelIcon).width === '18px' && getComputedStyle(document.querySelector('#modelIcon')).width === '20px';
    const originalProfiles = state.settings.modelProfiles.length;
    openSettings('models');
    addModelProfile.click();
    const profileAdded = state.settings.modelProfiles.length === originalProfiles + 1 && Boolean(document.querySelector('[data-delete-profile]'));
    const requiredModelIconsAvailable = MODEL_ICONS.length >= 120 && ['ri:grok-ai-fill', 'hugeicons:kimi-ai', 'simple-icons:minimax'].every((icon) => document.querySelector('[data-model-icon="' + icon + '"]'));
    const modelIconsLoadProgressively = modelIconGrid.querySelectorAll('[data-model-icon]').length <= 48 && MODEL_ICONS.length >= 120;
    document.querySelector('[data-model-icon="hugeicons:kimi-ai"]').click();
    const customModelIconSelected = state.settings.modelProfiles.find((profile) => profile.id === state.editingProfileId)?.icon === 'hugeicons:kimi-ai' && Boolean(editingProviderIcon.querySelector('.iconify-remote'));
    const modelDragHandlesVisible = modelProfilesList.querySelectorAll('.model-drag-handle[draggable="true"]').length === state.settings.modelProfiles.length;
    const modelIdsBefore = state.settings.modelProfiles.map((profile) => profile.id);
    const modelIdsAfter = moveOrderedValue(modelIdsBefore, modelIdsBefore[0], modelIdsBefore[1], true);
    const modelsById = new Map(state.settings.modelProfiles.map((profile) => [profile.id, profile]));
    state.settings.modelProfiles = modelIdsAfter.map((id) => modelsById.get(id));
    renderModelProfiles(); fillModelProfile();
    const modelOrderChanges = modelProfilesList.querySelector('.model-profile-wrap')?.dataset.profileCard === modelIdsBefore[1];
    toast('Модель успешно переключена');
    const toastStyle = getComputedStyle(document.querySelector('#toast'));
    const toastIsReadableAndAboveMenus = Number(toastStyle.zIndex) >= 500 && parseFloat(toastStyle.minHeight) >= 48 && Boolean(document.querySelector('#toast > i')) && Boolean(document.querySelector('#toast .toast-timer')) && document.querySelector('#toast').closest('dialog[open]');
    document.querySelector('#toast').classList.remove('show'); document.body.appendChild(document.querySelector('#toast'));
    cancelSettings();
    const cancelRestoredSettings = state.settings.modelProfiles.length === originalProfiles;
    await new Promise((resolve) => setTimeout(resolve, 220));
    openSettings('permissions');
    const permissionScopeControlsVisible = document.querySelectorAll('[data-permission-scope]').length === 2;
    document.querySelector('[data-permission-scope="global"]').click();
    permissionSandboxMode.value = 'full'; permissionSandboxMode.dispatchEvent(new Event('change', { bubbles: true }));
    const globalFullAccessConfigured = state.settings.permissionDefaults.sandboxMode === 'full';
    document.querySelector('[data-permission-scope="project"]').click();
    const projectInheritsGlobalPermissions = currentProjectPermissions().sandboxMode === 'full';
    permissionSandboxMode.value = 'workspace'; permissionSandboxMode.dispatchEvent(new Event('change', { bubbles: true }));
    const projectOverrideConfigured = state.settings.projectPermissionOverrides[state.workspace] && currentProjectPermissions().sandboxMode === 'workspace';
    useGlobalPermissions.click();
    const projectCanReturnToGlobal = !state.settings.projectPermissionOverrides[state.workspace] && currentProjectPermissions().sandboxMode === 'full';
    permissionSandboxMode.value = 'workspace'; permissionSandboxMode.dispatchEvent(new Event('change', { bubbles: true }));
    const toolToggleCount = toolAccessList.querySelectorAll('[data-tool-toggle]').length;
    const dockerToggle = toolAccessList.querySelector('[data-tool-toggle="docker"]');
    dockerToggle.click();
    const toolDisabledPerProject = currentProjectPermissions().disabledTools.includes('docker');
    const originalFileRules = currentProjectPermissions().fileRules.length;
    addFileReadRule.click();
    const granularRuleAdded = currentProjectPermissions().fileRules.length === originalFileRules + 1;
    cancelSettings();
    const granularRuleCancelled = currentProjectPermissions().fileRules.length === originalFileRules;
    await new Promise((resolve) => setTimeout(resolve, 220));
    openSettings('general');
    const originalAlias = state.projectAliases[state.workspace];
    renameProjectButton.click();
    renameProjectInput.value = 'Smoke Project';
    renameProjectForm.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    const projectRenamed = settingsProjectTitle.textContent === 'Smoke Project';
    if (originalAlias) state.projectAliases[state.workspace] = originalAlias; else delete state.projectAliases[state.workspace];
    localStorage.setItem('xacode.projectAliases', JSON.stringify(state.projectAliases));
    cancelSettings();
    await new Promise((resolve) => setTimeout(resolve, 220));
    openSettings('customizations');
    const originalInstructionCount = state.settings.instructionProfiles.length;
    addInstructionProfile.click();
    instructionNameInput.value = 'Smoke Instructions';
    instructionNameInput.dispatchEvent(new Event('input', { bubbles: true }));
    instructionPromptInput.value = 'Always answer briefly.';
    instructionPromptInput.dispatchEvent(new Event('input', { bubbles: true }));
    activateInstructionProfile.click();
    temperatureEnabled.checked = true;
    temperatureEnabled.dispatchEvent(new Event('change', { bubbles: true }));
    temperatureInput.value = '1.3';
    temperatureInput.dispatchEvent(new Event('input', { bubbles: true }));
    const instructionProfilesWork = state.settings.instructionProfiles.length === originalInstructionCount + 1 && state.settings.activeInstructionProfileId === state.editingInstructionId && state.settings.customInstructionsEnabled && instructionProfilesList.textContent.includes('Smoke Instructions');
    const temperatureControlsWork = state.settings.temperatureEnabled && state.settings.temperature === 1.3 && temperatureValue.textContent === '1.3' && !temperatureControls.classList.contains('disabled');
    cancelSettings();
    await new Promise((resolve) => setTimeout(resolve, 220));
    const localFullAccessEnabled = await handleLocalSlashCommand('enable', [{ type: 'command', id: 'fullaccess' }]) && currentProjectPermissions().sandboxMode === 'full';
    const localFullAccessDisabled = await handleLocalSlashCommand('disable', [{ type: 'command', id: 'fullaccess' }]) && currentProjectPermissions().sandboxMode === 'workspace';
    const permissionsCommandHandled = await handleLocalSlashCommand('', [{ type: 'command', id: 'permissions' }]) && document.querySelector('#settingsDialog')?.open && document.querySelector('[data-settings-page="permissions"]')?.classList.contains('active');
    cancelSettings();
    await new Promise((resolve) => setTimeout(resolve, 220));
    const firstWorkspace = state.workspace;
    const firstActiveId = state.activeId;
    const reorderNow = new Date().toISOString();
    const reorderWorkspace = firstWorkspace + '-reorder-probe';
    const reorderProjectChat = { id: 'project-reorder-chat', title: 'Project reorder', workspace: reorderWorkspace, createdAt: reorderNow, updatedAt: reorderNow, pinned: false, messages: [{ id: 'project-reorder-message', role: 'user', content: 'probe', createdAt: reorderNow }] };
    const reorderSiblingChat = { id: 'chat-reorder-chat', title: 'Chat reorder', workspace: firstWorkspace, createdAt: reorderNow, updatedAt: reorderNow, pinned: false, messages: [{ id: 'chat-reorder-message', role: 'user', content: 'probe', createdAt: reorderNow }] };
    state.conversations.push(reorderProjectChat, reorderSiblingChat);
    renderSidebar();
    const projectKeysBefore = [...conversationList.querySelectorAll('.project-group')].map((item) => item.dataset.project);
    state.projectOrder = moveOrderedValue(projectKeysBefore, projectKeysBefore[0], projectKeysBefore[1], true);
    localStorage.setItem('xacode.projectOrder', JSON.stringify(state.projectOrder));
    renderSidebar();
    const projectOrderChanges = conversationList.querySelector('.project-group')?.dataset.project === projectKeysBefore[1] && conversationList.querySelectorAll('.project-group[draggable="true"]').length >= 2 && !conversationList.querySelector('.project-drag-handle');
    const firstWorkspaceChatList = conversationList.querySelector('[data-project="' + CSS.escape(firstWorkspace) + '"] .project-conversations');
    const chatIdsBefore = [...firstWorkspaceChatList.querySelectorAll('[data-chat-row]')].map((item) => item.dataset.chatRow);
    state.chatOrder[firstWorkspace] = moveOrderedValue(chatIdsBefore, chatIdsBefore[0], chatIdsBefore[1], true);
    localStorage.setItem('xacode.chatOrder', JSON.stringify(state.chatOrder));
    renderSidebar();
    const reorderedChatList = conversationList.querySelector('[data-project="' + CSS.escape(firstWorkspace) + '"] .project-conversations');
    const chatOrderChanges = reorderedChatList.querySelector('[data-chat-row]')?.dataset.chatRow === chatIdsBefore[1] && reorderedChatList.querySelectorAll('.project-chat[draggable="true"]').length >= 2 && !reorderedChatList.querySelector('.chat-drag-handle');
    state.conversations = state.conversations.filter((conversation) => !['project-reorder-chat', 'chat-reorder-chat'].includes(conversation.id));
    state.projectOrder = []; state.chatOrder = {}; localStorage.removeItem('xacode.projectOrder'); localStorage.removeItem('xacode.chatOrder'); renderSidebar();
    state.workspace = firstWorkspace + '-not-current';
    newChat.click();
    const topNewChatUsesCurrentDirectory = activeConversation().workspace === firstWorkspace;
    state.conversations = state.conversations.filter((conversation) => conversation.id !== state.activeId);
    state.activeId = firstActiveId;
    state.workspace = firstWorkspace;
    renderSidebar();
    const projectPlus = [...document.querySelectorAll('[data-project-new-chat]')].find((button) => button.dataset.projectNewChat === firstWorkspace);
    projectPlus.click();
    const projectPlusCreatesChatInDirectory = activeConversation().workspace === firstWorkspace;
    state.conversations = state.conversations.filter((conversation) => conversation.id !== state.activeId);
    state.activeId = firstActiveId;
    state.workspace = firstWorkspace;
    render();
    state.settings.projectPermissions[firstWorkspace] = { ...LOCAL_PROJECT_PERMISSIONS, commandRules: [{ effect: 'allow', command: 'npm test' }] };
    state.settings.projectPermissionOverrides[firstWorkspace] = true;
    state.workspace = firstWorkspace + '-other';
    const projectPermissionsIsolated = currentProjectPermissions().commandRules.length === 0;
    state.workspace = firstWorkspace;
    const markdown = simpleMarkdown('| Имя | Статус |\n| --- | --- |\n| XaCode | **Готово** |\n\n- [x] Проверено\n\n[Ссылка](https://example.com)');
    const markdownFeatures = markdown.includes('<table>') && markdown.includes('type="checkbox"') && markdown.includes('<a href=');
    const mathMarkdown = simpleMarkdown('\\[\\frac{\\sqrt{144}}{\\sqrt{16}}\\]' + '\n' + '<details><summary>Решение</summary>Ответ: \\(3\\) или $3$</details>');
    const mathProbe = document.createElement('div');
    mathProbe.className = 'bubble';
    mathProbe.innerHTML = mathMarkdown;
    document.body.appendChild(mathProbe);
    const displayMathProbe = mathProbe.querySelector('.markdown-math.display');
    const positionedMathPart = displayMathProbe.querySelector('.vlist > span[style*="top"]');
    const mathFormatting = mathMarkdown.includes('katex') && mathMarkdown.includes('mfrac') && mathMarkdown.includes('sqrt') && mathMarkdown.includes('markdown-details') && mathProbe.querySelectorAll('.markdown-math.inline').length === 2;
    const mathLayoutDetails = { boxSizing: getComputedStyle(mathProbe.querySelector('.mfrac')).boxSizing, overflowY: getComputedStyle(displayMathProbe).overflowY, scrollHeight: displayMathProbe.scrollHeight, clientHeight: displayMathProbe.clientHeight, formulaHeight: displayMathProbe.querySelector('.katex').getBoundingClientRect().height };
    const mathLayoutStable = mathLayoutDetails.boxSizing === 'content-box' && mathLayoutDetails.overflowY === 'hidden' && mathLayoutDetails.formulaHeight > 30 && positionedMathPart?.style.top && getComputedStyle(positionedMathPart).top !== '0px';
    mathProbe.remove();
    const diagramProbe = document.createElement('div');
    diagramProbe.className = 'bubble';
    const fence = String.fromCharCode(96).repeat(3);
    diagramProbe.innerHTML = simpleMarkdown(fence + 'mermaid\ngraph TD\nA[User] --> B[Agent]\n' + fence + '\n\n' + fence + 'ascii\n+------+\n| API  |\n+------+\n' + fence);
    document.body.appendChild(diagramProbe);
    await renderMermaidDiagrams(diagramProbe);
    const mermaidRendering = Boolean(diagramProbe.querySelector('.mermaid-card.rendered svg'));
    const asciiDiagramRendering = Boolean(diagramProbe.querySelector('.ascii-diagram'));
    diagramProbe.remove();
    activeConversation().messages.push({ id: 'spinner-probe', role: 'status', content: 'Executing Tool: inspectworkspace', createdAt: new Date().toISOString() });
    state.runningIds.add(state.activeId);
    renderMessages();
    const requestedToolSpinnerVisible = Boolean(document.querySelector('[data-message="spinner-probe"] .execution-bars-spinner animateTransform'));
    activeConversation().messages.pop();
    state.runningIds.delete(state.activeId);
    renderMessages();
    showSlashMenu('/');
    const slashCommandCount = slashMenu.querySelectorAll('[data-slash-command]').length;
    const slashUsesMentionLayout = slashMenu.querySelectorAll('.mention-option').length === slashCommandCount;
    slashSelectedIndex = slashItems.length - 1; showSlashMenu('/');
    await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    const slashMenuScrolls = slashMenu.scrollHeight > slashMenu.clientHeight && slashMenu.scrollTop > 0;
    slashSelectedIndex = 0;
    mentionQuery = ''; mentionResults = []; mentionSelectedIndex = mentionQuickItems.length - 1; showMentionPopover();
    await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    const mentionMenuScrolls = mentionPopover.scrollHeight > mentionPopover.clientHeight && mentionPopover.scrollTop > 0;
    mentionPopover.classList.add('hidden'); mentionQuery = null; mentionSelectedIndex = 0;
    clearPrompt();
    const setPromptCaret = (node, offset) => { const range = document.createRange(); range.setStart(node, offset); range.collapse(true); const selection = getSelection(); selection.removeAllRanges(); selection.addRange(range); promptInput.focus(); };
    promptInput.textContent = 'до @pack после';
    setPromptCaret(promptInput.firstChild, 8);
    promptInput.dispatchEvent(new Event('input', { bubbles: true }));
    await new Promise((resolve) => setTimeout(resolve, 30));
    promptInput.dispatchEvent(new KeyboardEvent('keydown', { key: 'Tab', bubbles: true, cancelable: true }));
    const inlineFileByTab = promptTokens().some((token) => token.type === 'file' && token.path.endsWith('package.json'));
    const firstToken = promptInput.querySelector('.prompt-token');
    const leadingRange = document.createRange(); leadingRange.selectNodeContents(promptInput.firstChild);
    const tokenHasNoForcedGap = Math.abs(leadingRange.getBoundingClientRect().right - firstToken.getBoundingClientRect().left) < 1;
    const capabilityCount = mentionQuickItems.length;
    insertTextAtCaret(' /go');
    promptInput.dispatchEvent(new KeyboardEvent('keydown', { key: 'Tab', bubbles: true, cancelable: true }));
    const inlineCommandByTab = promptTokens().some((token) => token.type === 'command' && token.id === 'goal');
    const richParts = promptParts();
    const richMessage = { id: 'rich-prompt-test', role: 'user', content: promptText(true), promptParts: richParts, createdAt: new Date().toISOString() };
    activeConversation().messages.push(richMessage); renderMessages();
    const sentPromptTokenVisible = Boolean(document.querySelector('[data-message="rich-prompt-test"] .message-prompt-token.command'));
    const sentPromptOrderPreserved = richParts.filter((part) => part.type === 'token').map((part) => part.tokenType).join(',') === 'file,command';
    activeConversation().messages.pop(); renderMessages();
    promptInput.dispatchEvent(new KeyboardEvent('keydown', { key: 'Backspace', bubbles: true, cancelable: true }));
    const atomicTokenBackspace = !promptTokens().some((token) => token.type === 'command');
    await addAttachment('C:\\Temp\\ordinary.txt');
    const separateFileUpload = state.attachments.some((item) => item.path.endsWith('ordinary.txt') && !item.image);
    const originalWorkspaceForProject = state.workspace;
    const originalActiveForProject = state.activeId;
    document.querySelector('[data-projects-action="blank"]').click();
    await new Promise((resolve) => setTimeout(resolve, 30));
    const randomProjectCreated = state.workspace.includes('.xacode_project') && state.activeId !== originalActiveForProject;
    state.conversations = state.conversations.filter((conversation) => conversation.id !== state.activeId);
    state.workspace = originalWorkspaceForProject;
    state.activeId = originalActiveForProject;
    document.querySelector('[data-projects-action="select"]').click();
    await new Promise((resolve) => setTimeout(resolve, 30));
    const newProjectUsesFolderPicker = state.workspace === window.xacode.__testWorkspace() && state.activeId !== originalActiveForProject;
    state.conversations = state.conversations.filter((conversation) => conversation.id !== state.activeId);
    state.workspace = originalWorkspaceForProject;
    state.activeId = originalActiveForProject;
    const scheduledTasksRemoved = !document.querySelector('#scheduledButton') && !slashCommands.some((command) => command.id === 'schedule');
    const pasteEvent = { clipboardData: { items: [{ type: 'image/png' }] }, preventDefault() {} };
    await pasteClipboardImage(pasteEvent);
    const pastedImage = state.attachments.some((item) => item.image && item.path.endsWith('.png'));
    const imagePreviewMatchesTarget = getComputedStyle(document.querySelector('.attachment-image-preview')).width === '80px' && getComputedStyle(document.querySelector('.attachment-image-preview')).height === '78px';
    const choiceConversationId = state.activeId;
    state.runningIds.add(choiceConversationId);
    newConversation(state.workspace);
    const otherChatUsableWhileRunning = !isConversationRunning() && !modelButton.disabled;
    const runningControl = document.querySelector('[data-stop-chat="' + choiceConversationId + '"]');
    const sidebarRunningIndicatorVisible = Boolean(runningControl?.querySelector('.running-spinner animateTransform'));
    const stopSquareOnlyOnHover = getComputedStyle(runningControl?.querySelector('span')).opacity === '0';
    const runningChatIsCompact = getComputedStyle(runningControl?.closest('.project-chat')).minHeight === '35px' && !runningControl?.closest('.project-chat').querySelector('.chat-token-estimate');
    runningControl?.click();
    await new Promise((resolve) => setTimeout(resolve, 0));
    const sidebarStopWorks = window.xacode.__testStoppedConversation() === choiceConversationId && !state.runningIds.has(choiceConversationId);
    window.xacode.__testTriggerChoice({ conversationId: choiceConversationId, requestId: 'choice-test', question: 'Разрешить команду?\npython --version', options: ['Разрешить один раз', 'Запретить'] });
    const choiceHiddenOnNewChat = inlineChoice.classList.contains('hidden') && !document.querySelector('.composer-wrap').classList.contains('choice-active');
    const ownerMarkedUnread = state.conversations.find((conversation) => conversation.id === choiceConversationId).unread === true;
    const unreadIndicatorStyle = getComputedStyle(document.querySelector('[data-chat-row="' + choiceConversationId + '"]'), '::before');
    const unreadIndicatorImproved = unreadIndicatorStyle.width === '2px' && parseFloat(unreadIndicatorStyle.height) >= 14 && unreadIndicatorStyle.borderRadius !== '50%';
    const waitingNotificationSent = window.xacode.__testNotifications().some((notification) => notification.conversationId === choiceConversationId);
    openConversation(choiceConversationId);
    state.runningIds.delete(choiceConversationId);
    const inlineChoiceVisible = !inlineChoice.classList.contains('hidden') && inlineChoiceOptions.children.length === 2;
    const permissionInputHidden = document.querySelector('.inline-choice-custom').classList.contains('hidden');
    inlineChoiceOptions.querySelector('button').click();
    const choiceWaitsForSubmit = window.xacode.__testLastChoice() === '' && !inlineChoice.classList.contains('hidden');
    inlineChoiceSubmit.click();
    const choiceReturned = window.xacode.__testLastChoice() === 'Разрешить один раз' && inlineChoice.classList.contains('hidden');
    activeConversation().totalTokensUsed = 0;
    activeConversation().lastCountedRunId = '';
    activeConversation().currentRunId = 'smoke-run-1';
    handleAgentUpdate({ conversationId: state.activeId, content: '⏹ *Task stopped by user.*\n📊 *Task Execution Metrics:*\n• *Tokens Spent (this run):* 123' });
    const stoppedTokensVisible = activeConversation().lastRunTokens === 123 && activeConversation().messages.some((message) => message.content.includes('Остановлено пользователем'));
    activeConversation().currentRunId = 'smoke-run-2';
    handleAgentUpdate({ conversationId: state.activeId, content: '📊 *Task Execution Metrics:*\n• *Tokens Spent (this run):* 77' });
    const totalChatTokensAccumulate = activeConversation().totalTokensUsed === 200;
    handleAgentUpdate({ conversationId: state.activeId, content: '📊 *Task Execution Metrics:*\n• *Tokens Spent (this run):* 77' });
    const runTokensCountOnce = activeConversation().totalTokensUsed === 200;
    const tokenEstimateHiddenInRow = document.querySelector('.chat-token-estimate') === null;
    const activeChatRow = document.querySelector('[data-chat-row="' + state.activeId + '"]');
    showChatHover(state.activeId, activeChatRow);
    const tokenTotalVisibleOnHover = document.querySelector('#projectHoverCard')?.textContent.includes('Всего потрачено: 200 токенов') === true;
    const projectDeleteUsesTrashStyle = getComputedStyle(document.querySelector('.project-delete')).backgroundColor === 'rgba(0, 0, 0, 0)';
    const lastUiStateRemembered = localStorage.getItem('xacode.lastConversationId') === state.activeId && localStorage.getItem('xacode.lastView') === state.view;
    const refreshedHomeCopy = Boolean(document.querySelector('#emptyState .ph-code-block')) && !emptyState.textContent.includes('—');
    renderMessages();
    await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    const chatOpensAtBottom = Math.abs(messages.scrollTop - Math.max(0, messages.scrollHeight - messages.clientHeight)) < 2 && getComputedStyle(messages).scrollBehavior === 'auto';
    const contextCursor = getComputedStyle(contextIndicator).cursor;
    return { composerModelIconAligned, profileAdded, requiredModelIconsAvailable, modelIconsLoadProgressively, customModelIconSelected, modelDragHandlesVisible, modelOrderChanges, toastIsReadableAndAboveMenus: Boolean(toastIsReadableAndAboveMenus), projectOrderChanges, chatOrderChanges, cancelRestoredSettings, permissionScopeControlsVisible, globalFullAccessConfigured, projectInheritsGlobalPermissions, projectOverrideConfigured, projectCanReturnToGlobal, granularRuleAdded, granularRuleCancelled, toolToggleCount, toolDisabledPerProject, projectRenamed, instructionProfilesWork, temperatureControlsWork, localFullAccessEnabled, localFullAccessDisabled, permissionsCommandHandled, topNewChatUsesCurrentDirectory, projectPlusCreatesChatInDirectory, projectPermissionsIsolated, providerCount: providerInput.options.length, markdownFeatures, mathFormatting, mathLayoutStable, mermaidRendering, asciiDiagramRendering, requestedToolSpinnerVisible, slashCommandCount, slashUsesMentionLayout, slashMenuScrolls, mentionMenuScrolls, inlineFileByTab, tokenHasNoForcedGap, capabilityCount, inlineCommandByTab, sentPromptTokenVisible, sentPromptOrderPreserved, atomicTokenBackspace, separateFileUpload, randomProjectCreated, newProjectUsesFolderPicker, scheduledTasksRemoved, pastedImage, imagePreviewMatchesTarget, otherChatUsableWhileRunning, sidebarRunningIndicatorVisible, stopSquareOnlyOnHover, runningChatIsCompact, sidebarStopWorks, choiceHiddenOnNewChat, ownerMarkedUnread, unreadIndicatorImproved, waitingNotificationSent, inlineChoiceVisible, permissionInputHidden, choiceWaitsForSubmit, choiceReturned, stoppedTokensVisible, totalChatTokensAccumulate, runTokensCountOnce, tokenEstimateHiddenInRow, tokenTotalVisibleOnHover, projectDeleteUsesTrashStyle, lastUiStateRemembered, refreshedHomeCopy, chatOpensAtBottom, contextCursor, chooseApplicationApi: typeof window.xacode.chooseWorkspaceApp === 'function' };
  } catch (error) { return { error: error.stack || error.message }; } })()`);
  console.log(JSON.stringify(result));
  window.destroy(); app.quit();
});
