const { app, BrowserWindow } = require('electron');
const path = require('path');

app.whenReady().then(async () => {
  const window = new BrowserWindow({ width: 1280, height: 820, show: false, webPreferences: { preload: path.join(__dirname, 'visual-smoke-preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: false, backgroundThrottling: false } });
  await window.loadFile(path.join(__dirname, '..', 'src', 'desktop', 'renderer', 'index.html'));
  await new Promise((resolve) => setTimeout(resolve, 350));
  const result = await window.webContents.executeJavaScript(String.raw`(async () => { try {
    const originalProfiles = state.settings.modelProfiles.length;
    openSettings('models');
    addModelProfile.click();
    const profileAdded = state.settings.modelProfiles.length === originalProfiles + 1 && Boolean(document.querySelector('[data-delete-profile]'));
    cancelSettings();
    const cancelRestoredSettings = state.settings.modelProfiles.length === originalProfiles;
    await new Promise((resolve) => setTimeout(resolve, 220));
    openSettings('permissions');
    const toolToggleCount = toolAccessList.querySelectorAll('[data-tool-toggle]').length;
    const dockerToggle = toolAccessList.querySelector('[data-tool-toggle="docker"]');
    dockerToggle.click();
    const toolDisabledPerProject = currentProjectPermissions().disabledTools.includes('docker');
    const originalFileRules = currentProjectPermissions().fileRules.length;
    addFileRule.click();
    const granularRuleAdded = currentProjectPermissions().fileRules.length === originalFileRules + 1;
    cancelSettings();
    const granularRuleCancelled = currentProjectPermissions().fileRules.length === originalFileRules;
    await new Promise((resolve) => setTimeout(resolve, 220));
    openSettings('general');
    const originalAlias = state.projectAliases[state.workspace];
    renameProjectButton.click();
    renameProjectInput.value = 'Smoke Project';
    renameProjectForm.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    const projectRenamed = settingsProjectTitle.textContent === 'Smoke Project';
    if (originalAlias) state.projectAliases[state.workspace] = originalAlias; else delete state.projectAliases[state.workspace];
    localStorage.setItem('xacode.projectAliases', JSON.stringify(state.projectAliases));
    cancelSettings();
    await new Promise((resolve) => setTimeout(resolve, 220));
    const firstWorkspace = state.workspace;
    const firstActiveId = state.activeId;
    state.workspace = firstWorkspace + '-not-current';
    newChat.click();
    const topNewChatUsesCurrentDirectory = activeConversation().workspace === firstWorkspace;
    state.conversations = state.conversations.filter((conversation) => conversation.id !== state.activeId);
    state.activeId = firstActiveId;
    state.workspace = firstWorkspace;
    renderSidebar();
    const projectPlus = [...document.querySelectorAll('[data-project-new-chat]')].find((button) => button.dataset.projectNewChat === firstWorkspace);
    projectPlus.click();
    const projectPlusCreatesChatInDirectory = activeConversation().workspace === firstWorkspace;
    state.conversations = state.conversations.filter((conversation) => conversation.id !== state.activeId);
    state.activeId = firstActiveId;
    state.workspace = firstWorkspace;
    render();
    state.settings.projectPermissions[firstWorkspace] = { ...LOCAL_PROJECT_PERMISSIONS, commandRules: [{ effect: 'allow', command: 'npm test' }] };
    state.workspace = firstWorkspace + '-other';
    const projectPermissionsIsolated = currentProjectPermissions().commandRules.length === 0;
    state.workspace = firstWorkspace;
    const markdown = simpleMarkdown('| Имя | Статус |\n| --- | --- |\n| XaCode | **Готово** |\n\n- [x] Проверено\n\n[Ссылка](https://example.com)');
    const markdownFeatures = markdown.includes('<table>') && markdown.includes('type="checkbox"') && markdown.includes('<a href=');
    showSlashMenu('/');
    const slashCommandCount = slashMenu.querySelectorAll('[data-slash-command]').length;
    const originalWorkspaceForProject = state.workspace;
    const originalActiveForProject = state.activeId;
    document.querySelector('[data-projects-action="blank"]').click();
    await new Promise((resolve) => setTimeout(resolve, 30));
    const randomProjectCreated = state.workspace.includes('.xacode_project') && state.activeId !== originalActiveForProject;
    state.conversations = state.conversations.filter((conversation) => conversation.id !== state.activeId);
    state.workspace = originalWorkspaceForProject;
    state.activeId = originalActiveForProject;
    document.querySelector('[data-projects-action="select"]').click();
    await new Promise((resolve) => setTimeout(resolve, 30));
    const newProjectUsesFolderPicker = state.workspace === window.xacode.__testWorkspace() && state.activeId !== originalActiveForProject;
    state.conversations = state.conversations.filter((conversation) => conversation.id !== state.activeId);
    state.workspace = originalWorkspaceForProject;
    state.activeId = originalActiveForProject;
    const scheduledTasksRemoved = !document.querySelector('#scheduledButton') && !slashCommands.some((command) => command.id === 'schedule');
    const pasteEvent = { clipboardData: { items: [{ type: 'image/png' }] }, preventDefault() {} };
    await pasteClipboardImage(pasteEvent);
    const pastedImage = state.attachments.some((item) => item.image && item.path.endsWith('.png'));
    window.xacode.__testTriggerChoice({ requestId: 'choice-test', question: 'Разрешить команду?\npython --version', options: ['Разрешить один раз', 'Запретить'] });
    const inlineChoiceVisible = !inlineChoice.classList.contains('hidden') && inlineChoiceOptions.children.length === 2;
    const permissionInputHidden = document.querySelector('.inline-choice-custom').classList.contains('hidden');
    inlineChoiceOptions.querySelector('button').click();
    const choiceReturned = window.xacode.__testLastChoice() === 'Разрешить один раз' && inlineChoice.classList.contains('hidden');
    handleAgentUpdate({ conversationId: state.activeId, content: '⏹ *Task stopped by user.*\n📊 *Task Execution Metrics:*\n• *Tokens Spent (this run):* 123' });
    const stoppedTokensVisible = activeConversation().lastRunTokens === 123 && activeConversation().messages.some((message) => message.content.includes('Остановлено пользователем'));
    const contextCursor = getComputedStyle(contextIndicator).cursor;
    return { profileAdded, cancelRestoredSettings, granularRuleAdded, granularRuleCancelled, toolToggleCount, toolDisabledPerProject, projectRenamed, topNewChatUsesCurrentDirectory, projectPlusCreatesChatInDirectory, projectPermissionsIsolated, providerCount: providerInput.options.length, markdownFeatures, slashCommandCount, randomProjectCreated, newProjectUsesFolderPicker, scheduledTasksRemoved, pastedImage, inlineChoiceVisible, permissionInputHidden, choiceReturned, stoppedTokensVisible, contextCursor, chooseApplicationApi: typeof window.xacode.chooseWorkspaceApp === 'function' };
  } catch (error) { return { error: error.stack || error.message }; } })()`);
  console.log(JSON.stringify(result));
  window.destroy(); app.quit();
});
